== Building

=== Prerequisites

[[jdk]]
==== Java Development Kit (JDK)

In order to build the project you must have JDK 11{plus} (f.e. OpenJDK) installed.


Remember to ensure that "javac" and "java" are in your path (or symlinked).

....
JAVA_HOME=/location/to/javahome
export JAVA_HOME

PATH=$JAVA_HOME/bin:$PATH
export PATH
      
....

[[maven]]
==== Apache Maven

You must have Apache Maven installed on your system.

Remember to ensure that "mvn" are in your path (or symlinked).

....
MVN_HOME=/location/to/mvnhome
export MVN_HOME

PATH=$MVN_HOME/bin:$PATH
export PATH
      
....

==== Git

You must have Git installed on your system.

Remember to ensure that "git" are in your path (or symlinked).

[[obtainingthesource]]
=== Obtaining the source code

[[forking]]
==== Forking the repository

The IronJacamar repository is located at:

....
https://github.com/ironjacamar/ironjacamar
      
....

Press the "Fork" button in order to fork the repository to your own
GitHub account.

Clone your repository to your machine using

....
git clone git@github.com:<your_account>/ironjacamar.git
      
....

Next add the upstream repository as a remote location:

....
cd ironjacamar
git remote add upstream git@github.com:ironjacamar/ironjacamar.git
      
....


[[compiling]]
=== Compiling the source code

In order to build the IronJacamar project you execute:

....
mvn install
....

[[creating_a_patch]]
=== Creating a patch

Our user guide explains in the "I would like to implement a feature"
section how to get started on a writing a new feature or submitting a
patch to the project.

You should develop your feature on a Git branch using

....
git checkout -b <feature_name>
    
....

Once you are done you will need to rebase your work with the latest
master

....
git fetch upstream
git rebase -i upstream/master
    
....

You will need to resolve any conflicts of course. Note, that all pull
requests must be rebased against upstream master in order to get merged.

Then push the feature to your repository

....
git push origin <feature_name>
    
....

Go to your account on GitHub.com and submit a pull request via the "Pull
request" button

....
https://www.github.com/<your_account>/ironjacamar
    
....

Remember to select the correct branch, fill in the subject with a short
description of the feature, and fill in the description with the full
description of the feature.

If your feature / bug-fix applies to multiple branches you will need to
submit multiple pull requests - one pull request per branch.
