== Preface

[[about]]
== About IronJacamar

The goal of the IronJacamar project is to provide an implementation of
the Jakarta Connectors 2.1 specification.

The specification can be found here:
https://jakarta.ee/specifications/connectors/2.1/jakarta-connectors-spec-2.1

The IronJacamar project is licensed under the GNU LESSER GENERAL PUBLIC
LICENSE 2.1 (LGPL 2.1) license.

[[whythename]]
== Why IronJacamar ?

The Jakarta Connectors container can be viewed as a foundation inside an 
application server as it provides connectivity to the other containers 
such that they can communicate with EISes. Iron is often used as foundation
in building houses too.

The Jacamar bird family which lives in Central and South America are
glossy elegant birds with long bills and tails. Why we picked the
Jacamar family is left as an exercise for the reader :)

== Versions

This section contains the highlights of the IronJacamar releases. A full
description of each release can be found through our issue tracking
system at http://issues.jboss.org/browse/JBJCA.

== License

Copyright © 2014 Red Hat, Inc. and others.

The text of and illustrations in this document are licensed by Red Hat
under a Creative Commons Attribution–Share Alike 3.0 Unported license
("CC-BY-SA").

An explanation of CC-BY-SA is available at
http://creativecommons.org/licenses/by-sa/3.0/. In accordance with
CC-BY-SA, if you distribute this document or an adaptation of it, you
must provide the URL for the original version.

Red Hat, as the licensor of this document, waives the right to enforce,
and agrees not to assert, Section 4d of CC-BY-SA to the fullest extent
permitted by applicable law.
